<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Run on CHROME"
           tests="12"
           failures="1"
           errors="0"
           skipped="0"
           time="165,886">
  <properties />
            <testcase name="TC_08_IncorrectDomainAfterAtSignInEmail" time="16,504" classname="com.maybestore.Testcase_Login">
                <failure type="java.lang.AssertionError"
                  message="expected [Thông tin đăng nhập không hợp lệ.] but found [Số điện thoại không hợp lệ.]"
              >
<![CDATA[java.lang.AssertionError: expected [Thông tin đăng nhập không hợp lệ.] but found [Số điện thoại không hợp lệ.]
  org.testng.Assert.fail(Assert.java:96)
  org.testng.Assert.failNotEquals(Assert.java:776)
  org.testng.Assert.assertEqualsImpl(Assert.java:137)
  org.testng.Assert.assertEquals(Assert.java:118)
  org.testng.Assert.assertEquals(Assert.java:442)
  commons.BaseTest.verifyEquals(BaseTest.java:107)
  com.maybestore.Testcase_Login.TC_08_IncorrectDomainAfterAtSignInEmail(Testcase_Login.java:187)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:568)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:648)
  org.testng.TestRunner.run(TestRunner.java:505)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
  org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
  java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  java.base/java.lang.Thread.run(Thread.java:833)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="TC_05_InCorrectEmailAndCorrectPass" time="13,469" classname="com.maybestore.Testcase_Login" />
                <testcase name="TC_06_InvalidEmailFormat" time="12,411" classname="com.maybestore.Testcase_Login" />
                <testcase name="TC_04_CorrectEmailAndIncorrectPass" time="13,379" classname="com.maybestore.Testcase_Login" />
                <testcase name="TC_01_EmptyEmailAndPasswordFields" time="14,512" classname="com.maybestore.Testcase_Login" />
                <testcase name="TC_07_MissingDomainAfterAtSignInEmail" time="12,376" classname="com.maybestore.Testcase_Login" />
                <testcase name="TC_11_DeletedEmail_LoginWithPassword" time="15,247" classname="com.maybestore.Testcase_Login" />
                <testcase name="TC_12_ValidEmailAndPassword_Login" time="13,324" classname="com.maybestore.Testcase_Login" />
                <testcase name="TC_02_CorrectEmailFieldValidation" time="12,981" classname="com.maybestore.Testcase_Login" />
                <testcase name="TC_09_MissingCharactersBeforeAtSignInEmail" time="13,081" classname="com.maybestore.Testcase_Login" />
                <testcase name="TC_03_CorrectPassFieldValidation" time="14,410" classname="com.maybestore.Testcase_Login" />
                <testcase name="TC_10_DisabledEmail_LoginWithPassword" time="14,192" classname="com.maybestore.Testcase_Login" />
      
</testsuite>
