<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MAI" failures="1" tests="12" name="com.maybestore.Testcase_Login" time="219.320" errors="0" timestamp="22 thg 5 2024 01:15:25 GMT" skipped="0">
  <testcase classname="com.maybestore.Testcase_Login" name="TC_03_CorrectPassFieldValidation" time="17.385"/>
  <testcase classname="com.maybestore.Testcase_Login" name="TC_07_MissingDomainAfterAtSignInEmail" time="15.660"/>
  <testcase classname="com.maybestore.Testcase_Login" name="TC_11_DeletedEmail_LoginWithPassword" time="18.684"/>
  <testcase classname="com.maybestore.Testcase_Login" name="TC_08_IncorrectDomainAfterAtSignInEmail" time="20.617">
    <failure message="expected [Thông tin đăng nhập không hợp lệ.] but found [Số điện thoại không hợp lệ.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Thông tin đăng nhập không hợp lệ.] but found [Số điện thoại không hợp lệ.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at commons.BaseTest.verifyEquals(BaseTest.java:107)
at com.maybestore.Testcase_Login.TC_08_IncorrectDomainAfterAtSignInEmail(Testcase_Login.java:187)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- TC_08_IncorrectDomainAfterAtSignInEmail -->
  <testcase classname="com.maybestore.Testcase_Login" name="TC_12_ValidEmailAndPassword_Login" time="17.433"/>
  <testcase classname="com.maybestore.Testcase_Login" name="TC_02_CorrectEmailFieldValidation" time="17.200"/>
  <testcase classname="com.maybestore.Testcase_Login" name="TC_09_MissingCharactersBeforeAtSignInEmail" time="14.363"/>
  <testcase classname="com.maybestore.Testcase_Login" name="TC_10_DisabledEmail_LoginWithPassword" time="30.697"/>
  <testcase classname="com.maybestore.Testcase_Login" name="TC_05_InCorrectEmailAndCorrectPass" time="16.171"/>
  <testcase classname="com.maybestore.Testcase_Login" name="TC_06_InvalidEmailFormat" time="15.905"/>
  <testcase classname="com.maybestore.Testcase_Login" name="TC_04_CorrectEmailAndIncorrectPass" time="17.107"/>
  <testcase classname="com.maybestore.Testcase_Login" name="TC_01_EmptyEmailAndPasswordFields" time="18.098"/>
</testsuite> <!-- com.maybestore.Testcase_Login -->
